Bump dependencies
artipie/npm-adapter pull request #118
Opened 2020-09-17 15:51 UTC by olenagerasimova

Bumped our dependencies and made corresponding corrections.

2020-09-17 15:53 UTC, olenagerasimova commented
@artipie/contributors please review, I cannot assign PRs in this repo

2020-09-18 07:52 UTC, olegmoz requested changes
@olenagerasimova thanks, please see one comment

2020-09-18 07:52 UTC, olegmoz commented on npm-proxy-adapter/pom.xml
> +      <version>0.24</version>
@olenagerasimova shouldn't we bump it to `0.28` which is latest version?

2020-09-18 07:52 UTC, olegmoz commented
@olenagerasimova please also note that CI checks are failing for some reason

2020-09-18 12:15 UTC, olenagerasimova commented
@olegmoz all fixed, please, merge and release

2020-09-18 12:39 UTC, olegmoz approved these changes
@olenagerasimova thanks

2020-09-18 12:39 UTC, merged

2020-09-18 12:48 UTC, olegmoz commented
@yegor256 please touch `.rultor` so we can release

2020-09-18 12:53 UTC, yegor256 commented
@olegmoz done

2020-09-18 12:53 UTC, olegmoz commented
@yegor256 thanks!

2020-09-18 12:54 UTC, olegmoz commented
@rultor release, tag=`0.6.2`

2020-09-18 12:54 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/23363-694849947)

2020-09-18 12:56 UTC, 0crat commented
Job `gh:artipie/npm-adapter#118` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/54bef5b6-9b71-4a0d-881d-7cba7ad7a7fa, version: 0.54.5, hash: ${buildNumber} -->

2020-09-18 13:00 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz @olenagerasimova Oops, I failed. You can see the full log [here](https://www.rultor.com/t/23363-694849947) (spent 6min)

```
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
\u001b[1mCaused by\u001b[m: org.apache.maven.reporting.MavenReportException: \u001b[1;31m
Exit code: 1 - /home/r/repo/npm-hosted-adapter/src/main/java/com/artipie/npm/Tarballs.java:39: error: bad use of '>'
 * absolute URL: /@scope/package-name -> http://host:port/base-path/@scope/package-name.
                                       ^

Command line was: /usr/lib/jvm/java-11-openjdk/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/r/repo/npm-hosted-adapter/target/apidocs' dir.
\u001b[m
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.doExecuteJavadocCommandLine (\u001b[1mAbstractJavadocMojo.java:5861\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeJavadocCommandLine (\u001b[1mAbstractJavadocMojo.java:5737\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport (\u001b[1mAbstractJavadocMojo.java:2176\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.JavadocJar.doExecute (\u001b[1mJavadocJar.java:199\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.execute (\u001b[1mAbstractJavadocMojo.java:1935\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:137\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
[\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
container 3000a02e9bbd4e7a67f8729a84c2548a0f2c91502c77c556a72771dc46b7fa97 is dead
Fri Sep 18 15:00:33 CEST 2020
```

2020-09-18 13:17 UTC, olegmoz commented
@rultor release, tag=`0.6.2`

2020-09-18 13:17 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/23363-694861940)

2020-09-18 13:18 UTC, olegmoz commented
@rultor release, tag=`0.6.2`

2020-09-18 13:23 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz @olenagerasimova Oops, I failed. You can see the full log [here](https://www.rultor.com/t/23363-694861940) (spent 6min)

```
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
\u001b[1mCaused by\u001b[m: org.apache.maven.reporting.MavenReportException: \u001b[1;31m
Exit code: 1 - /home/r/repo/npm-hosted-adapter/src/main/java/com/artipie/npm/Tarballs.java:39: error: bad use of '>'
 * absolute URL: /@scope/package-name -> http://host:port/base-path/@scope/package-name.
                                       ^

Command line was: /usr/lib/jvm/java-11-openjdk/bin/javadoc @options @packages

Refer to the generated Javadoc files in '/home/r/repo/npm-hosted-adapter/target/apidocs' dir.
\u001b[m
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.doExecuteJavadocCommandLine (\u001b[1mAbstractJavadocMojo.java:5861\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeJavadocCommandLine (\u001b[1mAbstractJavadocMojo.java:5737\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.executeReport (\u001b[1mAbstractJavadocMojo.java:2176\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.JavadocJar.doExecute (\u001b[1mJavadocJar.java:199\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugins.javadoc.AbstractJavadocMojo.execute (\u001b[1mAbstractJavadocMojo.java:1935\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:137\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
[\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
container d2d153812f55292684d7bc3ccf79d04e4cc1b183580054da747d1b414359bdaf is dead
Fri Sep 18 15:23:25 CEST 2020
```

2020-09-18 13:24 UTC, olegmoz commented
@rultor release, tag=`0.6.2`

2020-09-18 13:26 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/23363-694862638)

2020-09-18 13:34 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz Done! FYI, the full log is [here](https://www.rultor.com/t/23363-694862638) (took me 8min)

2020-09-18 13:35 UTC, olegmoz commented
@olenagerasimova release complete

2020-09-18 13:37 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz @olenagerasimova Invalid release tag `0.6.2` specified. There is already a release `0.6.2` newer than the given release in this repository.

2020-09-18 13:37 UTC, rultor commented
> @rultor release, tag=`0.6.2`

@olegmoz I'm sorry, I don't understand you :( Check [this page](http://doc.rultor.com/basics.html) and try again please