#156 - added IT and dummy slice for deprecate command
artipie/npm-adapter pull request #166
Opened 2021-01-25 12:55 UTC by olenagerasimova

Part of #156 
Adde IT for `npm deprecate` and dummy (for now) slice.

2021-01-25 13:38 UTC, genryxy requested changes
@olenagerasimova thanks, one suggestion

2021-01-25 13:38 UTC, genryxy commented on src/main/java/com/artipie/npm/http/NpmSlice.java
> +                ),
@olenagerasimova probably to move pattern for deprecate to `DeprecateSlice`

2021-01-25 14:51 UTC, olenagerasimova commented
@genryxy thanks, corrected

2021-01-25 14:59 UTC, genryxy approved these changes
@olenagerasimova thanks, approve

2021-01-26 10:59 UTC, genryxy commented
@g4s8 could you please check/merge

2021-01-26 13:03 UTC, g4s8 requested changes
@olenagerasimova please see my comment

2021-01-26 13:03 UTC, g4s8 commented on src/main/java/com/artipie/npm/http/DeprecateSlice.java
> +public final class DeprecateSlice implements Slice {
@olenagerasimova do we really need a class just to keep some static field?

2021-01-26 13:10 UTC, olenagerasimova commented on src/main/java/com/artipie/npm/http/DeprecateSlice.java
> +public final class DeprecateSlice implements Slice {
@g4s8 this class will be properly implemented in the next PR

2021-01-26 13:13 UTC, g4s8 approved these changes
@olenagerasimova got it, thanks

2021-01-26 13:27 UTC, merged

2021-01-26 14:05 UTC, 0crat commented
Job `gh:artipie/npm-adapter#166` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/948ce054-1b98-4925-8d11-a74f619525f2, version: 0.55, hash: ${buildNumber} -->