#154 - Add IT and slice  for npm unpublish
artipie/npm-adapter pull request #167
Opened 2021-01-25 13:50 UTC by genryxy

Part of #154 
Add IT and slice without realization  for `npm unpublish`

2021-01-25 14:50 UTC, olenagerasimova requested changes
@genryxy thanks, just two minor suggestions

2021-01-25 14:50 UTC, olenagerasimova commented on src/test/java/com/artipie/npm/NpmUnpublishIT.java
> +        this.storage = new FileStorage(this.tmp);
@genryxy I'd suggest to use `InMemory` storage here, I do not see any need in `FileStorage`

2021-01-25 14:50 UTC, olenagerasimova commented on src/test/java/com/artipie/npm/NpmUnpublishIT.java
> +            .addFilesTo(this.storage, Key.ROOT);
@genryxy seems like there is no need for line brake in this expression

2021-01-25 14:59 UTC, genryxy commented
@olenagerasimova thanks, used `InMemoryStorage`

2021-01-25 15:09 UTC, olenagerasimova approved these changes
@genryxy thanks, good to merge

2021-01-26 10:59 UTC, genryxy commented
@g4s8 could you please check/merge

2021-01-26 13:01 UTC, g4s8 commented
@genryxy can you please check CI errors after rebase.

2021-01-26 13:13 UTC, genryxy commented
@g4s8 fixed

2021-01-26 13:14 UTC, merged

2021-01-26 13:35 UTC, 0crat commented
Job `gh:artipie/npm-adapter#167` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/69531713-221c-42f0-be4c-e1e47b839a5e, version: 0.55, hash: ${buildNumber} -->