#154 - Entire package unpublish
artipie/npm-adapter pull request #171
Opened 2021-01-26 14:46 UTC by genryxy

Part of #154 
Implemented unpublishing of entire package

2021-01-26 15:29 UTC, olenagerasimova requested changes
@genryxy just one suggestion, please, check

2021-01-26 15:29 UTC, olenagerasimova commented on src/test/java/com/artipie/npm/http/UnpublishForceSliceTest.java
> +            this.storage.exists(new Key.From("@hello/simple-npm-project", "meta.json"))
@genryxy would not it be better to check that entire project directory was removed, not just `meta.json`?

2021-01-26 16:36 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-01-26 19:57 UTC, olenagerasimova approved these changes
@genryxy thanks, approving

2021-01-27 08:31 UTC, merged

2021-01-27 09:05 UTC, 0crat commented
Job `gh:artipie/npm-adapter#171` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/ec30ee6f-dec2-4f75-a00c-fd64b57500b0, version: 0.55, hash: ${buildNumber} -->