(#168) Improve code coverage
artipie/npm-adapter pull request #183
Opened 2021-02-08 06:44 UTC by baudoliver7

#168

Write unit tests for :
- Misc classes
- Npm files
- Npm proxy HTTP files

2021-02-08 08:09 UTC, g4s8 commented
@baudoliver7 please try to make smaller PRs next time, no more than 300 lines of change, it'll be easier to review. Also, I'll reduce license header to make changes more informative

2021-02-08 10:25 UTC, baudoliver7 commented
@g4s8 well noted !

2021-02-08 12:06 UTC, genryxy requested changes
@baudoliver7 thanks, please see comments

2021-02-08 12:06 UTC, genryxy commented on src/test/java/com/artipie/npm/MetaUpdateByTgzTest.java
> +final class MetaUpdateByTgzTest {
@baudoliver7 sorry but working on this class is still in progress. See #36. I think it would be better to add test cases after closing this issue if there are not enough tests.

2021-02-08 13:10 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/misc/DescSortedVersionsTest.java
> +    void getNextValue() {
@baudoliver7 I think `generateNextValue` could be a better one :)

2021-02-08 14:48 UTC, genryxy commented on src/test/java/com/artipie/npm/misc/DescSortedVersionsTest.java
> +    void getNextValue() {
@baudoliver7 probably `sortsVersionsInDescendingOrder`

2021-02-08 20:49 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/misc/DescSortedVersionsTest.java
> +    void getNextValue() {
@genryxy Oh yes, you are right ! I was thinking about `NextSafeAvailablePort` :)

2021-02-08 21:00 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +    void downloadMetaWorksWithoutPathPrefix() {
@genryxy same for `DownloadPackageSlice`

2021-02-09 05:27 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +    }
@genryxy Right !

2021-02-09 05:51 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            ),
@genryxy I afraid that this code is not duplicated. The second one is for `meta.meta` file.

2021-02-09 06:12 UTC, genryxy commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            ),
@baudoliver7 by the way, you can create a local variable, for example `tgz=@hello/simple-npm-project/-/@hello/simple-npm-project-1.0.1.tgz`, and use this one for creating variable and with `.meta` in this way `String.format("%s.meta", tgz)`. The same idea for path for obtaining resources.

2021-02-09 06:17 UTC, genryxy commented on src/test/java/com/artipie/npm/misc/NextSafeAvailablePortTest.java
> +final class NextSafeAvailablePortTest {
@baudoliver7 okay, got it.

2021-02-09 06:20 UTC, genryxy commented on src/test/java/com/artipie/npm/misc/NextSafeAvailablePortTest.java
> +    }
@baudoliver7 please divide this test case into two different tests and use `MatcherAssert` from hamcrest instead of `org.junit.Assert`

2021-02-09 06:22 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            ),
@genryxy I agree with you. Let's do that :)

2021-02-09 06:42 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +    void finish() {
@genryxy Ok

2021-02-09 06:44 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> + * DownloadAssetSlice tests.
@genryxy Ok

2021-02-09 06:49 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/misc/DescSortedVersionsTest.java
> + * DescSortedVersions tests.
@genryxy Ok

2021-02-09 06:50 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadPackageSliceTest.java
> + * DownloadPackageSlice tests.
@genryxy Ok

2021-02-09 07:45 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadPackageSliceTest.java
> +final class DownloadPackageSliceTest {
@genryxy Ok

2021-02-09 07:47 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/MetaUpdateByTgzTest.java
> +final class MetaUpdateByTgzTest {
@genryxy Ok

2021-02-09 07:48 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            )
@genryxy  Ok

2021-02-09 07:54 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/misc/NextSafeAvailablePortTest.java
> +    }
@genryxy I suggest to parameterize this test case since it is about invalid port

2021-02-09 07:57 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/misc/NextSafeAvailablePortTest.java
> +    }
@genryxy like this :
```java
  void failsByInvalidPort() {
      Throwable thrown =
          Assertions.assertThrows(
              IllegalArgumentException.class,
              () -> new NextSafeAvailablePort(1023).value()
          );
      Assert.assertThat(thrown.getMessage(), Matchers.is("Invalid start port: 1023"));
      thrown =
          Assertions.assertThrows(
              IllegalArgumentException.class,
              () -> new NextSafeAvailablePort(49_152).value()
          );
      Assert.assertThat(thrown.getMessage(), Matchers.is("Invalid start port: 49152"));
  }
```

2021-02-09 08:04 UTC, baudoliver7 commented on pom.xml
> +                      <minimum>0.74</minimum>
@genryxy this task is too big to be resolved in one ticket. That is why I created a new puzzle to package `com.artipie.npm`.

2021-02-09 08:06 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +    }
@genryxy the second suggestion seems better.

2021-02-09 08:14 UTC, baudoliver7 commented on pom.xml
> +                      <minimum>0.74</minimum>
@genryxy Now, it is 0.70 after removing `MetaUpdateByTgzTest`.

2021-02-09 08:15 UTC, baudoliver7 commented on pom.xml
> +                      <minimum>0.74</minimum>
@genryxy It is for missing instructions ratio only. All others coverage ratio have been set to 75.

2021-02-09 08:19 UTC, genryxy commented on pom.xml
> +                      <minimum>0.74</minimum>
@baudoliver7 thanks, got it

2021-02-09 08:22 UTC, genryxy commented on src/test/java/com/artipie/npm/misc/NextSafeAvailablePortTest.java
> +    }
@baudoliver7 okay, it looks better. One minor comment: please use constructor instead of invocation static methods if it is possible (just a preference for project). In this case it would be better to use `new IsEqual<>(value)` .

2021-02-09 09:02 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/misc/NextSafeAvailablePortTest.java
> +    }
@genryxy Ok

2021-02-09 09:13 UTC, baudoliver7 commented
@genryxy Some changes have been made.

2021-02-09 09:27 UTC, genryxy requested changes
@baudoliver7 thanks, please see comments

2021-02-09 09:27 UTC, genryxy commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +            );
@baudoliver7 It would be better to take the content of `simple-npm-project/package.json` because content of file and joined string are very similar.

2021-02-09 09:27 UTC, genryxy commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            );
@baudoliver7 check for emptiness in this case by specifying `ctx/` instead of `ctx`

2021-02-09 09:27 UTC, genryxy commented on src/test/java/com/artipie/npm/proxy/http/DownloadPackageSliceTest.java
> +            );
@baudoliver7 the same here

2021-02-09 09:27 UTC, genryxy commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +        ).get();
@baudoliver7 probably to extract this saving to a separate private method to make `setUp` shorter and more understandable

2021-02-09 09:27 UTC, genryxy commented on src/test/java/com/artipie/npm/proxy/http/DownloadPackageSliceTest.java
> +        ).get();
@baudoliver7 the same here

2021-02-09 10:01 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            );
@genryxy I afraid we can do that because of :
```suggestion
final AssetPath path = new AssetPath(pathprefix);
```
We should not have slash in `pathprefix.`

2021-02-09 10:01 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadPackageSliceTest.java
> +            );
@genryxy Ditto

2021-02-09 10:05 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +            );
@genryxy Yes, IMHO, it is more readable and better to not depend on a file, just on a text.

2021-02-09 10:30 UTC, genryxy commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            );
@baudoliver7 yeah, I missed this statement. `prefix.replaceAll("/$")` will solve this problem.

2021-02-09 10:36 UTC, genryxy commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +            );
@baudoliver7 but this is the main file and is used in many tests. From my point of view, line `new String(new TestResource(path).asBytes())` is more readable than string joining with plenty of exclusions for quotation marks. The most important thing is that string just duplicates the contents of the file

2021-02-10 10:18 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +            );
@genryxy I agree with you on this last point. Let's do that.

2021-02-10 11:04 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +            );
@genryxy I get it now. But I did it in another manner :)

2021-02-10 11:05 UTC, baudoliver7 commented on src/test/java/com/artipie/npm/proxy/http/DownloadAssetSliceTest.java
> +        ).get();
@genryxy Good

2021-02-10 11:27 UTC, baudoliver7 commented
@genryxy Another changes have been made :)

2021-02-10 11:30 UTC, baudoliver7 commented
@genryxy Another changes have been made :)

2021-02-10 13:00 UTC, genryxy approved these changes
@baudoliver7 thanks, looks good to me
@g4s8 please check/merge

2021-02-11 09:07 UTC, g4s8 approved these changes
@baudoliver7 thanks

2021-02-11 09:10 UTC, merged

2021-02-11 10:03 UTC, 0crat commented
Job `gh:artipie/npm-adapter#183` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/3d3c89ff-6e28-4361-b221-0e90a6b886c5, version: 0.55, hash: ${buildNumber} -->