(#185) Make license headers short
artipie/npm-adapter pull request #186
Opened 2021-02-08 11:30 UTC by baudoliver7

#185

- Change files license headers
- Set up Qulice plugin to support this change

2021-02-08 12:24 UTC, g4s8 commented
@baudoliver7 it seems something goes wrong, please see CI checks for this PR

2021-02-08 13:02 UTC, baudoliver7 commented
@g4s8 I'm looking for that. It's about Qulice. It seems that Qulice is ignoring LICENSE.header despite of our configuration. I'm trying to override it.

2021-02-08 13:20 UTC, baudoliver7 commented
@g4s8 Findbugs is complaining about reliance on default encoding in 4 parts of code. What default encoding should we use here ?

2021-02-08 14:48 UTC, g4s8 commented
> @g4s8 Findbugs is complaining about reliance on default encoding in 4 parts of code. What default encoding should we use here ?

@baudoliver7 I don't think encoding is a problem here:
```
 [INFO] Checkstyle: src/main/java/com/artipie/npm/misc/NextSafeAvailablePort.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/misc/JsonFromPublisher.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/misc/DateTimeNowStr.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/misc/package-info.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/misc/DescSortedVersions.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/misc/LastVersion.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/package-info.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/Tarballs.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/NpmPublishJsonToMetaSkelethon.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Checkstyle: src/main/java/com/artipie/npm/MetaUpdate.java[2]: Line does not match expected header line of ' * The MIT License (MIT)'. (HeaderCheck)
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
some license headers didn't match: https://github.com/artipie/npm-adapter/pull/186/checks?check_run_id=1854282410

2021-02-10 19:21 UTC, baudoliver7 commented
@g4s8 I was talking about some reliance errors from FindBugs after overriding qulice plugin configuration. You can see these errors in the last commit.

2021-02-10 19:21 UTC, baudoliver7 commented
@g4s8 I was talking about some reliance errors from FindBugs after overriding qulice plugin configuration. You can see these errors in the last commit.

2021-02-10 20:05 UTC, baudoliver7 commented
@g4s8 I used another maven settings to override qulice configuration. But I was talking about reliance on default encoding errors from FindBugs. You can see it in the last commit building.

2021-02-11 09:06 UTC, g4s8 requested changes
@baudoliver7 please check my comment on `pom.xml`

2021-02-11 09:06 UTC, g4s8 commented on pom.xml
> +                <configuration combine.self="override">
@baudoliver7 the `override` option overrides plugin configuration defined in parent pom. Also, the plugin is enabled from parent pom profile as well, so I'd just add a `pluginManagement` configuration without redefining `qulice` profile and plugin.

2021-02-11 11:46 UTC, baudoliver7 commented on pom.xml
> +                <configuration combine.self="override">
@g4s8 I'm afraid that it doesn't work. I have already tried this and it gave me a syntax error in pom file because maven merge the two plugin configurations and we end up with two qulice plugins in `pluginManagement` tag. This commit is an example [767a663](https://github.com/artipie/npm-adapter/commit/767a663440a162c2f7c0a028f66abb06c6395ea6). You could get more explanations [here](https://www.generacodice.com/en/articolo/264403/Maven2+-+problem+with+pluginManagement+and+parent-child+relationship#boxSoluzioneDescrizione).

2021-02-12 13:43 UTC, g4s8 commented on pom.xml
> +                <configuration combine.self="override">
@baudoliver7 the proble is that we can't accept pull request if it removes base qulice configuration from parent pom

2021-02-13 10:53 UTC, baudoliver7 commented on pom.xml
> +                <configuration combine.self="override">
@g4s8 please, let me have a look to find a method that accords with principles.

2021-02-13 15:11 UTC, baudoliver7 commented on pom.xml
> +                <configuration combine.self="override">
@g4s8 All things are fine now. To make it work, I had to add this little configuration to `pom` file :
```xml
<profiles>
    <profile>
      <id>qulice</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.qulice</groupId>
            <artifactId>qulice-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>jcabi-qulice-check</id>
                <configuration>
                  <license>file:${basedir}/LICENSE.header</license>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```
It's mandatory because we execute jcabi-qulice-check which also setup LICENSE file.

2021-02-13 15:13 UTC, baudoliver7 commented
@g4s8 Please, check my latest changes.

2021-02-15 06:27 UTC, g4s8 requested changes
@baudoliver7 it seems now we have a duplication of configuration of plugins and re-defineing the profile from parent pom in project pom.

2021-02-15 06:27 UTC, g4s8 commented on pom.xml
> +  </profiles>
@baudoliver7 why do we need to re-define profile from parent pom here?

2021-02-15 09:24 UTC, baudoliver7 commented on pom.xml
> +  </profiles>
@g4s8 We need to do it because in parent pom, profile `qulice` defines also `LICENSE.txt` as license file in its configuration. However, it is just a refinement of license configuration for both `default` and `jcabi-qulice-check` qulice executions. We don't remove here base qulice configuration from parent pom.

2021-02-16 06:56 UTC, baudoliver7 commented
@g4s8 Please, see my answer to your question :)

2021-02-16 07:19 UTC, g4s8 commented on pom.xml
> +  </profiles>
@baudoliver7 there is no such things as profile configuration in maven, the profile is just a kind of scope that can be activated by some property or manually. Only plugin may have plugin configuration section. So redefining profile with plugin override is not correct. Please check how the configuration of the profile defined in parent pom could be changed in child pom: https://github.com/artipie/http/pull/288/files

Other usefull links:
 - https://stackoverflow.com/questions/10483180/what-is-pluginmanagement-in-mavens-pom-xml
 - https://maven.apache.org/pom.html
 - https://maven.apache.org/pom.html#plugin-management
 - https://maven.apache.org/pom.html#what-is-the-pom

2021-02-16 08:15 UTC, baudoliver7 commented on pom.xml
> +  </profiles>
@g4s8 Thx for these links. But IMHO, I think you miss something here. In parent pom, besides having this in `pluginManagement` tag :
```xml
<plugin>
  <groupId>com.qulice</groupId>
  <artifactId>qulice-maven-plugin</artifactId>
  <version>0.18.19</version>
  <configuration>
    <license>file:${basedir}/LICENSE.txt</license>
  </configuration>
</plugin>
```
 you have also this in `profiles` tag :
```xml
<profile>
  <!--
  Static quality analysis with Qulice and other tools.
  This profile is supposed to be activated in continuous
  integration environment, right before the final approval
  of the build. It runs a number of static code analysis
  tools to validate and approve the quality of source
  code and the SCM repository.
  @see http://www.jcabi.com/jcabi-parent/profile-qulice.html
  -->
  <id>qulice</id>
  <build>
    <plugins>
      <plugin>
        <!--
        Qulice-maven-plugin is a compound static analysis
        tool that aggregates Checkstyle, PMD, FindBugs,
        CodeNarc (for Groovy code) and a few other analyzers.
        Qulice also configures them correctly to enable the
        most important rules.
        @see http://www.qulice.com/qulice-maven-plugin/
        -->
        <groupId>com.qulice</groupId>
        <artifactId>qulice-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>jcabi-qulice-check</id>
            <phase>verify</phase>
            <goals>
              <goal>check</goal>
            </goals>
            <configuration>
              <license>file:${basedir}/LICENSE.txt</license>
              <excludes>
                <exclude>xml:.*</exclude>
              </excludes>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</profile>
```
as `qulice` profile definition.
You will notice that these two pieces of code define license file for Qulice plugin. When you execute `mvn install -Pqulice`, Qulice use license file defined in profile `qulice` regardless of what you set in `pluginManagement`. If profile `qulice` did not configure license file in parent pom, what you suggest in ticket #185 would have worked. But to make it work in our case, we have to say to profile `qulice` to use a new license file.

2021-02-16 13:08 UTC, baudoliver7 commented on pom.xml
> +  </profiles>
@g4s8 We got a very similar example in [takes pom](https://github.com/yegor256/takes/blob/master/pom.xml) where we redefine in child pom profile `qulice` to do something in configuration. That doesn't remove basis configuration of this profile.
```xml
<profile>
  <id>qulice</id>
  <build>
    <plugins>
      <plugin>
        <groupId>com.qulice</groupId>
        <artifactId>qulice-maven-plugin</artifactId>
        <version>${qulice.version}</version>
        <configuration>
          <excludes combine.children="append">
            <exclude>checkstyle:/src/site/resources/.*</exclude>
          </excludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
</profile>
```

2021-02-16 13:09 UTC, baudoliver7 commented
@g4s8 Please, see some new comments

2021-02-21 08:52 UTC, g4s8 commented
@baudoliver7 please check new commit in parent pom https://github.com/artipie/ppom/commit/8e56909fb486006106ceb3ccfe9c8e9f3a253da5 to help license file configuration for qulice plugin. Now you can just change Maven property for license file without qulice plugin configuration. It'll be available in `0.4.4` parent pom version.

2021-02-22 01:09 UTC, baudoliver7 commented
@g4s8 Changes done locally. Now, waiting for the version `0.4.4` to be deployed in Maven :)

2021-02-23 00:16 UTC, baudoliver7 commented
@g4s8 I tried to use version `0.4.5` of `artipie ppom` deployed in maven. It is good for qulice `default` check :
```cmd
3321 [INFO] --- qulice-maven-plugin:0.18.19:check (default) @ npm-adapter ---
3322 [INFO] Downloading from oss.sonatype.org: 
          https://oss.sonatype.org/content/groups/public/org/cactoos/cactoos/0.41/cactoos-0.41.pom
3323 [INFO] Downloaded from oss.sonatype.org:
... ... ... ... ...
3719 [INFO] Downloaded from oss.sonatype.org: 
          https://oss.sonatype.org/content/groups/public/org/apache/maven/enforcer/enforcer-api/1.0-beta-1/enforcer-api-1.0- 
          beta-1.jar (9.8 kB at 65 kB/s)
3720 [INFO] Calling org.apache.maven.plugins:maven-enforcer-plugin:1.0-beta-1:enforce...
3721  [INFO] This is not an SVN project
3722 [INFO] No dependency analysis in this project
3723 [INFO] Qulice quality check completed in 16s
```
But it fails on `jcabi-qulice-check` :
```cmd
3725 [INFO] --- qulice-maven-plugin:0.18.19:check (jcabi-qulice-check) @ npm-adapter ---
3726 [INFO] Checkstyle: src/test/java/com/artipie/npm/RelativePathTest.java[2]: Line does not match expected header line of 
          ' * The MIT License (MIT)'. (HeaderCheck)
... ... ... ... ...
3821 [INFO] Read our quality policy: http://www.qulice.com/quality.html
3822 [INFO] ------------------------------------------------------------------------
3823 [INFO] BUILD FAILURE
3824 [INFO] ------------------------------------------------------------------------
3825 [INFO] Total time:  01:58 min
3326 [INFO] Finished at: 2021-02-22T22:53:31Z
3327 [INFO] ------------------------------------------------------------------------
```
 To resolve it, I think you should define profile `qulice` in `artipie ppom` like this : 
```xml
<profile>
    <id>qulice</id>
    <build>
      <plugins>
        <plugin>
          <groupId>com.qulice</groupId>
          <artifactId>qulice-maven-plugin</artifactId>
          <executions>
              <execution>
                <id>jcabi-qulice-check</id>
                <configuration>
                  <license>file:${qulice.license}</license>
                </configuration>
              </execution>
          </executions>
        </plugin>
      </plugins>
    </build>
  </profile>
```
It will force `jcabi-qulice-check` to use our license file without changing basis configuration of profile `qulice` plugin.

2021-02-23 01:00 UTC, baudoliver7 commented
@g4s8 I opened for that issue [#53](https://github.com/artipie/ppom/issues/53) on `artipie ppom`.

2021-03-01 13:41 UTC, baudoliver7 commented
@g4s8 Things seem good now :) Please, see my changes.

2021-03-01 14:03 UTC, g4s8 approved these changes
@baudoliver7 thanks!

2021-03-01 14:06 UTC, merged