#154 - Implement unpublishing single version, add IT
artipie/npm-adapter pull request #189
Opened 2021-02-11 06:29 UTC by genryxy

Part of #154
Unpublishing single version was implemented. 
Added IT for removing single version when multiple versions are published and one version is published

2021-02-11 09:03 UTC, g4s8 requested changes
@genryxy please check my comments

2021-02-11 09:03 UTC, g4s8 commented on src/main/java/com/artipie/npm/http/UnpublishPutSlice.java
> +    private static String updateMeta(final JsonObject body, final JsonObject meta) {
@genryxy param names (`body` and `meta`) looks not very clean - both are the same kind of data but from different sources. I'd rename it to something like `patch` or `update` for new meta json and `source` or `origin` for origin json

2021-02-11 09:03 UTC, g4s8 commented on src/main/java/com/artipie/npm/http/UnpublishPutSlice.java
> +    private static String versionToRemove(final JsonObject body, final JsonObject meta) {
@genryxy and same here

2021-02-11 09:17 UTC, genryxy commented
@g4s8 thanks, renamed

2021-02-19 08:34 UTC, g4s8 approved these changes
@genryxy thanks

2021-02-19 08:34 UTC, merged

2021-02-19 09:14 UTC, 0crat commented
Job `gh:artipie/npm-adapter#189` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/8f4db864-980d-459b-bd4f-0491c27892de, version: 0.55, hash: ${buildNumber} -->