#184 - Fix getting file from archive by name
artipie/npm-adapter pull request #191
Opened 2021-02-19 07:52 UTC by genryxy

Closes #184 
Fixed getting file from archive by name

2021-02-19 08:39 UTC, g4s8 requested changes
@genryxy please check my comment

2021-02-19 08:39 UTC, g4s8 commented on pom.xml
> +        <artifactId>qulice-maven-plugin</artifactId>
@genryxy this plugin is enabled in `qulice` profile in parent pom. In this PR you're enabling it by default (outside of profile) with overridden configuration. If you want to extend plugin configuration defined in parent pom, the correct way is to specify it in `pluginManagement` section, e.g. like here: https://github.com/artipie/artipie/blob/master/pom.xml#L383
```

2021-02-19 09:04 UTC, genryxy commented
@g4s8 thanks, added `pluginManagement` section

2021-02-25 11:03 UTC, genryxy commented
@g4s8 could you please check/merge?

2021-02-25 12:40 UTC, g4s8 approved these changes
@genryxy thanks

2021-02-25 12:40 UTC, merged

2021-02-25 13:09 UTC, 0crat commented
Job `gh:artipie/npm-adapter#191` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/382a653d-d9b4-4123-90f3-baee2a2db74a, version: 0.55, hash: ${buildNumber} -->