#190: Improve test coverate
artipie/npm-adapter pull request #194
Opened 2021-02-23 16:16 UTC by andreoss

Per #190 

- Removed dead code
- Add few tests

2021-02-25 11:16 UTC, genryxy requested changes
@andreoss thanks, see some minor comments

2021-02-25 11:16 UTC, genryxy commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +        );
@andreoss let's use `Assertions.assertThrows(...).getMessage()` instead of `Matchers.hasToString`. And `new StringContains(...)` instead of `Matchers.containsString` according to [this rule](https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md#code-style)

2021-02-25 11:16 UTC, genryxy commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +            )
@andreoss the same here

2021-02-25 11:16 UTC, genryxy commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +            temp.toFile().exists(),
@andreoss remove reason according to [this](https://github.com/artipie/artipie/blob/master/CONTRIBUTING.md#code-style)

2021-02-25 11:16 UTC, genryxy commented on src/test/java/com/artipie/npm/RelativePathTest.java
> +        );
@andreoss the same here

2021-02-27 03:38 UTC, andreoss commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +        );
@genryxy It's a bad idea[1] to call methods on objects under test. I used `HasProperty` instead


[1]: https://www.yegor256.com/2017/05/17/single-statement-unit-tests.html

2021-02-27 03:41 UTC, andreoss commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +            temp.toFile().exists(),
@genryxy Done. Also added todo.

2021-02-27 03:43 UTC, andreoss commented on src/test/java/com/artipie/npm/RelativePathTest.java
> +        );
@genryxy Done

2021-02-27 16:32 UTC, genryxy commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
> +        );
@andreoss I'm not sure that fully understand what is bad to call methods directly on object because in any case we'll have two assertions in this method. But your approach with using `HasPropertyWithValue` suits me now

2021-02-27 16:34 UTC, genryxy requested changes
@andreoss please see one minor comment

2021-02-27 16:34 UTC, genryxy commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
>          );
@andreoss we have two assertions in this test therefore reasons should not be removed

2021-02-27 16:34 UTC, genryxy commented
@andreoss also there is build failure because qulice violations. Please fix them

2021-02-27 18:08 UTC, andreoss commented on src/test/java/com/artipie/npm/TgzArchiveTest.java
>          );
@genryxy Done

2021-02-27 18:11 UTC, genryxy approved these changes
@andreoss thanks, looks good to me
@g4s8 please check/merge

2021-03-05 08:29 UTC, olenagerasimova commented
@andreoss could you please resolve conflicts?

2021-03-09 06:56 UTC, olenagerasimova commented
@andreoss sorry, there are some conflicts again, could you please resolve?

2021-03-09 07:30 UTC, olenagerasimova submitted a review, later dismissed

2021-03-09 07:30 UTC, olenagerasimova commented
@g4s8 please merge

2021-03-09 08:35 UTC, g4s8 requested changes
@andreoss please check my comment about todo

2021-03-09 08:35 UTC, g4s8 commented on pom.xml
> +      -->
@andreoss this todo seems to be out of scope of #190 origin task

2021-03-09 13:49 UTC, andreoss commented on pom.xml
> +      -->
@g4s8 Removed it

2021-03-12 13:25 UTC, g4s8 approved these changes
@andreoss thanks

2021-03-12 13:29 UTC, merged

2021-03-12 14:17 UTC, 0crat commented
Job `gh:artipie/npm-adapter#194` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/f18c308f-4aac-49a4-9b1d-2ac05f9476bd, version: 0.55.1, hash: ${buildNumber} -->