#169 - Add IT, try to reproduce regex bug
artipie/npm-adapter pull request #195
Opened 2021-03-05 08:54 UTC by genryxy

Part of #169 
Add IT for installation published package using `npm publish` or `curl PUT`. These ITs work well

2021-03-05 09:33 UTC, olenagerasimova requested changes
@genryxy thanks, one suggestion

2021-03-05 09:33 UTC, olenagerasimova commented on src/test/java/com/artipie/npm/NpmIT.java
> +    void installsPublishedProject() throws Exception {
@genryxy I'd suggest to parameterize this test case as the previous one

2021-03-05 09:44 UTC, genryxy commented
@olenagerasimova thanks, corrected

2021-03-05 10:00 UTC, olenagerasimova submitted a review, later dismissed

2021-03-05 10:00 UTC, olenagerasimova commented
@g4s8 please take a look/merge

2021-03-09 07:14 UTC, genryxy commented
@olenagerasimova could you please take a look again because I made changes about naming which were supposed in another related PR

2021-03-09 07:32 UTC, olenagerasimova approved these changes
@genryxy thanks, I've accidentally pressed the wrong button in that PR

2021-03-09 07:33 UTC, olenagerasimova commented
@g4s8 please, take a look/merge

2021-03-12 13:25 UTC, g4s8 approved these changes
@genryxy thanks

2021-03-12 13:25 UTC, merged

2021-03-12 14:17 UTC, 0crat commented
Job `gh:artipie/npm-adapter#195` is not assigned, can't get performer

<!-- https://www.0crat.com/footprint/CT2E6TK9B/bedf2944-7170-43ad-9c85-f70b633bf7dc, version: 0.55.1, hash: ${buildNumber} -->