Do not use Vertx in HttpNpmRemote.java
artipie/npm-adapter pull request #295
Opened 2022-02-01 14:37 UTC by olenagerasimova

Part of https://github.com/artipie/artipie/issues/806 (migrate to artipie http-client instead of vertx client)

Remade `HttpNpmRemote.java` use artipie slice to obtain content from remote instead of using vertx client and corrected test. `NpmProxyITCase` is disabled for now and will be corrected as soon as `NpmProxy` migrates to artipie http-client instead of vertx client.

2022-02-03 13:17 UTC, olenagerasimova commented
@g4s8 ping

2022-02-03 13:23 UTC, g4s8 requested changes
@olenagerasimova please check my comment

2022-02-03 13:23 UTC, g4s8 commented on src/main/java/com/artipie/npm/proxy/HttpNpmRemote.java
> +        final AtomicReference<Headers> headers) {
I didn't get this design: why to provide future as parameter to async task isntead of returning it from method? And `headers` param looks inconsistent: it's not clear without reading method's code to understand in what moment this headers will be set. I'd suggest returning a pair of content and headers as future from this method: `CompletableFuture<Pair<Headers, Content>>`

2022-02-03 13:38 UTC, olenagerasimova commented
@g4s8 thanks, changed the design

2022-02-04 10:13 UTC, g4s8 requested changes
@olenagerasimova thanks, please check comment

2022-02-04 10:13 UTC, g4s8 commented on src/main/java/com/artipie/npm/proxy/HttpNpmRemote.java
> +                        .doOnTerminate(() -> term.complete(null));
I'm not sure this code really work: the publisher returned from this `performRemoteRequest` function is subscribed only after return; it can't produce any error before it subscribed; so it can produce any error only after `subscribe` call which is called after future completes. So in case of error this future always complete already completed future. I'd suggest just return publisher as is and allow subscriber to handle errors

2022-02-04 11:03 UTC, olenagerasimova commented on src/main/java/com/artipie/npm/proxy/HttpNpmRemote.java
> +                        .doOnTerminate(() -> term.complete(null));
@g4s8 please, check this PR https://github.com/artipie/http-client/pull/49, there were some problems (I do not remember what exactly) but in the end we came to this particular code in the proxy adapters that works.

2022-02-07 08:30 UTC, g4s8 commented on src/main/java/com/artipie/npm/proxy/HttpNpmRemote.java
> +                        .doOnTerminate(() -> term.complete(null));
@olenagerasimova I see, submitted a ticket to investigate it: #296

2022-02-07 08:30 UTC, g4s8 approved these changes
@olenagerasimova thanks

2022-02-07 08:31 UTC, merged